### ISSUE TITLE
Error with yo: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by binary64** [ifedu/generator-speedseed-cleanly-polymer-get-started#1]
C:\p\speedseed1>yo speedseed-cleanly-polymer-get-started
? Test? Mocha
TypeError: Cannot read property 'config' of undefined
    at setOptionsTemplateToGenerator (C:\Users\x\AppData\Roaming\npm\node_mo
dules\generator-speedseed-cleanly-polymer-get-started\node_modules\speedseed\Cla
ss\Config.js:47:39)
    at _setPrompting (C:\Users\x\AppData\Roaming\npm\node_modules\generator-
speedseed-cleanly-polymer-get-started\node_modules\speedseed\Class\Config.js:137
:17)
    at prompt.then (C:\Users\x\AppData\Roaming\npm\node_modules\generator-sp
eedseed-cleanly-polymer-get-started\node_modules\speedseed\Class\Config.js:161:1
3)

C:\p\speedseed1>dir /a
 Volume in drive C has no label.
 Volume Serial Number is x-x

 Directory of C:\p\speedseed1

01/10/2016  02:07    <DIR>          .
01/10/2016  02:07    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)   6,287,466,496 bytes free

C:\p\speedseed1>node -v
v6.7.0

**Comment by binary64** [comment]
Welp, looks like installing it via `yo speedseed` did the trick. An error message if I try and scaffold directly from this would be handy.

**Comment by ifedu** [comment]
You're right thanks!, I will add it in the next update greetings
